<!-- formulario de alta de pelicula-->
<form action="nueva" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre de la pelicula</label>
                <input required name="name" type="text" class="form-control">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label>Director</label>
                <input required name="director" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Fecha de estreno</label>
                <input required name="date" type="date" class="form-control">
            </div>
        </div>

    <div class="col-6">
    <button type="submit" class="btn btn-primary mt-2">Agregar pelicula</button>
    </div>
</form>