<form action="nuevaPuntuacion" method="POST" class="my-4">
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label>Puntuación</label>
                <input type="number" name="valoracion" min="1" max="10" required class="form-control">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label>Empresa</label>
                <input required name="empresa" type="text" class="form-control">
            </div>
        </div>

        <div class="col-6">
            <div class="form-group">
            <label>Película:</label>
            <select name="id_pelicula" required>
                <option value="" disabled selected>Selecciona una película</option>
                <?php foreach ($peliculas as $pelicula): ?>
                    <option value="<?php echo $pelicula->id_peliculas; ?>">
                        <?php echo $pelicula->nombre; ?>
                    </option>
                <?php endforeach; ?>
            </select>
            </div>
        </div>

    <div class="col-6">
    <button type="submit" class="btn btn-primary mt-2">Agregar puntuacion</button>
    </div>
</form>