<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>COSOFLIX</title>
</head>

<body>
    <!-- main header -->
    <header>
        <nav class="navbar bg-light">
            <a class="navbar-brand" href="">COSOFLIX</a>
            <div class="container-nav">
                <div class="container-fluid d-flex">
                        
                    <?php if($this->usuario): ?>
                    <h1 class="me-3"><?php echo $this->usuario->usuario?><h1>
                    <a class="navbar-brand" href="logout">Logout</a>
                    <?php else: ?>
                    <a class="navbar-brand" href="showLogin">Login</a>
                    <?php endif; ?>
                        
                </div>
            </div>
        </nav>
    </header>

   <main class="container mt-3"> 